### ISSUE TITLE
virtual keyboard bug on Android device when popup

### ISSUE THREAD

**Issue by slavanb** [kartik-v/yii2-editable#183]
On all android devices, when I try to enter text in a pop-up window, at this point the virtual keyboard closes on the android.
It is observed in all browsers.

echo \kartik\editable\Editable::widget([
                        'model' => $model,
                        'attribute' => 'LESSON_THEMA',
                        'asPopover' => true,
                        'size' => 'lg',
                        'submitOnEnter' => false,
                        'inputType' => \kartik\editable\Editable::INPUT_TEXTAREA,
                        'options' => ['class'=>'form-control','rows' => 5],
                    ]);
- [ ] Mobile

- yii2-editable version:  1.7.7

- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-editable without other plugins.

**Comment by slavanb** [comment]
fix this problem
in composer.json

"kartik-v/bootstrap-popover-x": "1.4.3"

./composer.phar update

after that clean cache in /backend/web/assets  - all to trash

**Comment by phrakon** [comment]
The problem still present. It happens because bootstrap-popover-x.js checks window resize instead of orientationchange event. When virtual keyboard is showing, triggers resize event. So, js code hides our popover (need redraw. it is too easy to re-init popover instead of to recalc its coordinates), popover input loses focus, keyboard hides :) So, we can't use virtual keyboard trying to focus popover input

I tested kartik's demo page via my cellular (perhaps, my code is wrong). It does not work too :(

**Comment by phrakon** [comment]
```
$(window).resize(function () {
                if ($dialog.hasClass('kv-popover-active')) {
                    // self.hide();
                    // setTimeout(function () {
                    //     self.show(true);
                    // }, 50);
                    self.refreshPosition();
                }
            });
```

The code above helped me to solve problem. But i have no idea how to do it better.

**Comment by kartik-v** [comment]
This is fixed via [this commit](https://github.com/kartik-v/bootstrap-popover-x/commit/2362dae35e06189e9266cf6a364d37e5e80f7614) as mentioned in kartik-v/bootstrap-popover-x#46
