### ISSUE TITLE
Feature Request: Inline editing mode

### ISSUE THREAD

**Issue by angelcoding** [kartik-v/yii2-editable#3]
Loving your work on this.

Do you plan to add an optional inline editing mode (rather than just popover) like x-editable allows?

**Comment by akorinek** [comment]
Plus one on this one, I would like to save users some clicks to open a window and then update a single number and then clicking "submit" again. If this could be done using a single edit field inline instead which submits the new value onBlur, that would be great.

**Comment by DiaaFares** [comment]
@kartik-v +1 for this feature, please do it as soon as possible,
I noticed that your Tabular Form extension have the ability to include widgets inline and make edits,
so I think you can port this ability to your grid extension easily.

**Comment by kartik-v** [comment]
Editable is not linked to how TabularForm renders it and is not straightforward as it seems - because of the various functionalities it offers. You need to consider all use cases... currently it is a separate form on its own (not a batch form) and has its ability to use in grids, place additional inputs before and after etc...  Will do so when I get time...  am strapped with time with other work... pls donate to help prioritize.

**Comment by kartik-v** [comment]
Editable is not linked to how TabularForm renders it and is not straightforward as it seems - because of the various functionalities it offers. You need to consider all use cases... currently it is a separate form on its own (not a batch form) and has its ability to use in grids, place additional inputs before and after etc...  This is in my plan to do soon... but am strapped with time with other work... pls donate to help prioritize.

**Comment by DiaaFares** [comment]
@kartik-v Thank you very much for your response, I Appreciate your work and I know you time is limited, 
Maybe @YasserHassan have time and can help to add this Feature?

**Comment by YasserHassan** [comment]
@DiaaFares surely I'll be glad to help whenever I can. Currently my available time is absorbed by the forms functionality but I'll look into this if I can dedicate the time.

**Comment by DiaaFares** [comment]
@YasserHassan جزاك الله خيراً يا أخي، والله يبارك في وقت ويعينك
أتمنى أن أرى قريباً هذه الميزة لأني محتاجها حالياً
دمت بخير يا أخي

**Comment by kartik-v** [comment]
BTW... I hope to push this feature by this weekend... do support by visiting sponsors on the website and removing adblockers.

**Comment by kartik-v** [comment]
Ok this is resolved now via the latest updated release v1.7.3. You can set a new property `asPopover` which defaults to `true`. Set it to `false` for INLINE using all the other options for a popove editable.

Check #58, #59, #60, #61, #62 for details of the enhancements.

Check the [Editable as Popover](http://demos.krajee.com/editable#usage-popover) and [Editable as Inline](http://demos.krajee.com/editable#usage-popover) demos and go through the [entire docs in general](http://demos.krajee.com/editable).

**Comment by YasserHassan** [comment]
Well done @kartik-v. Would it be easy to replace the default with one beside the submit and reset buttons? This would be better for big forms like the address form.

P.S: Could you release this documentation and examples on the website in a downloadable format? Would be a great addition.

**Comment by kartik-v** [comment]
Please read [Editable Settings section in docs](http://demos.krajee.com/editable#settings) for understanding all editable widget settings and how to control templates (for inline).

At this stage I do not have any personal time at all for managing or creating docs for download.

**Comment by YasserHassan** [comment]
@kartik-v, I know about the embedded documentation, it's very good. I appreciate the sheer amount of effort you've done in this project.

**Comment by DiaaFares** [comment]
@kartik-v thank you very much for your efforts,
you do it so fast! Is the changes you did was not a lot and the process was easy?
