### ISSUE TITLE
Illegal offset type in isset or empty when the $value is array variable

### ISSUE THREAD

**Issue by SAP55** [kartik-v/yii2-editable#49]
`Line` 367
```php
if (is_array($this->displayValueConfig) && !empty($this->displayValueConfig[$value])) {
    $this->displayValue = $this->displayValueConfig[$value];
}
```
Illegal offset type in isset or empty when the $value is array variable.

**Comment by kartik-v** [comment]
You can use displayValueConfig only for simple key value pairs and cannot set your key as arrays.

You must parse and send such data via your ajax controller action by calculating and returning the value in `output` property of the json encoded object.

I will enhance the widget to include an exception that prevents developers trying to set an array as a key in the displayValueConfig.

**Comment by SAP55** [comment]
OK no problem, but if I use the ```$value``` as array and don't set configuration into ```$this->displayValueConfig``` ( this array is empty) I still  get this error, because this line expression ```!empty($this->displayValueConfig[$value])```. I think you must add something like this ```... $$ !empty($this->displayValueConfig)``` before previously expression ```!empty($this->displayValueConfig[$value])```.

**Comment by kartik-v** [comment]
Note if your value is an array - it will never be displayed and hence you will face an array to string exception. There are two parts to the editable widget - the one which is displayed as a link before you click... and the other an input when you click to edit. The displayed part will throw up an array to string error - because it can never get display

So when your value is an array you must set `displayValue` which is a valid string... so its displayed and your `value` is used in your dropdown or other input that can read an array. For example:

```php
'value' => [1 => 'val1', 2 => 'val2'],
'displayValue' => 'val1, val2'
```

Also hope you probably noted the fix that I already provided with this issue (check history before). Upgrade to latest if you haven't.

**Comment by SAP55** [comment]
Thank you for your help.
